[package]
name = "noedb-txn"
description = "MVCC transaction manager: BEGIN/COMMIT/ROLLBACK, Snapshot Isolation, SSI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
noedb-storage = { workspace = true }
thiserror = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
