# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from noedb.v1 import sql_pb2 as noedb_dot_v1_dot_sql__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in noedb/v1/sql_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SqlStub(object):
    """Cluster-authenticated SQL service (auth via `x-noedb-auth` metadata).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/noedb.v1.Sql/Execute',
                request_serializer=noedb_dot_v1_dot_sql__pb2.SqlRequest.SerializeToString,
                response_deserializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
                _registered_method=True)
        self.Explain = channel.unary_unary(
                '/noedb.v1.Sql/Explain',
                request_serializer=noedb_dot_v1_dot_sql__pb2.SqlRequest.SerializeToString,
                response_deserializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/noedb.v1.Sql/Ping',
                request_serializer=noedb_dot_v1_dot_sql__pb2.PingRequest.SerializeToString,
                response_deserializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
                _registered_method=True)


class SqlServicer(object):
    """Cluster-authenticated SQL service (auth via `x-noedb-auth` metadata).
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Explain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=noedb_dot_v1_dot_sql__pb2.SqlRequest.FromString,
                    response_serializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.SerializeToString,
            ),
            'Explain': grpc.unary_unary_rpc_method_handler(
                    servicer.Explain,
                    request_deserializer=noedb_dot_v1_dot_sql__pb2.SqlRequest.FromString,
                    response_serializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=noedb_dot_v1_dot_sql__pb2.PingRequest.FromString,
                    response_serializer=noedb_dot_v1_dot_sql__pb2.SqlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'noedb.v1.Sql', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('noedb.v1.Sql', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sql(object):
    """Cluster-authenticated SQL service (auth via `x-noedb-auth` metadata).
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noedb.v1.Sql/Execute',
            noedb_dot_v1_dot_sql__pb2.SqlRequest.SerializeToString,
            noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Explain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noedb.v1.Sql/Explain',
            noedb_dot_v1_dot_sql__pb2.SqlRequest.SerializeToString,
            noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/noedb.v1.Sql/Ping',
            noedb_dot_v1_dot_sql__pb2.PingRequest.SerializeToString,
            noedb_dot_v1_dot_sql__pb2.SqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
