# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noedb/v1/sql.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'noedb/v1/sql.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12noedb/v1/sql.proto\x12\x08noedb.v1\"\x1b\n\nSqlRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x95\x01\n\x0bSqlResponse\x12%\n\x06result\x18\x01 \x01(\x0b\x32\x13.noedb.v1.ResultSetH\x00\x12\x11\n\x07\x65xplain\x18\x02 \x01(\tH\x00\x12\x1f\n\x04pong\x18\x03 \x01(\x0b\x32\x0f.noedb.v1.EmptyH\x00\x12#\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x12.noedb.v1.SqlErrorH\x00\x42\x06\n\x04\x62ody\"9\n\tResultSet\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\x12\x1b\n\x04rows\x18\x02 \x03(\x0b\x32\r.noedb.v1.Row\"\x14\n\x03Row\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\t\")\n\x08SqlError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xab\x01\n\x03Sql\x12\x36\n\x07\x45xecute\x12\x14.noedb.v1.SqlRequest\x1a\x15.noedb.v1.SqlResponse\x12\x36\n\x07\x45xplain\x12\x14.noedb.v1.SqlRequest\x1a\x15.noedb.v1.SqlResponse\x12\x34\n\x04Ping\x12\x15.noedb.v1.PingRequest\x1a\x15.noedb.v1.SqlResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noedb.v1.sql_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SQLREQUEST']._serialized_start=32
  _globals['_SQLREQUEST']._serialized_end=59
  _globals['_PINGREQUEST']._serialized_start=61
  _globals['_PINGREQUEST']._serialized_end=74
  _globals['_SQLRESPONSE']._serialized_start=77
  _globals['_SQLRESPONSE']._serialized_end=226
  _globals['_RESULTSET']._serialized_start=228
  _globals['_RESULTSET']._serialized_end=285
  _globals['_ROW']._serialized_start=287
  _globals['_ROW']._serialized_end=307
  _globals['_SQLERROR']._serialized_start=309
  _globals['_SQLERROR']._serialized_end=350
  _globals['_EMPTY']._serialized_start=352
  _globals['_EMPTY']._serialized_end=359
  _globals['_SQL']._serialized_start=362
  _globals['_SQL']._serialized_end=533
# @@protoc_insertion_point(module_scope)
