[package]
name = "noedb-planner"
description = "Logical and physical query planner for NoeDB (Volcano-style)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true

[lib]
name = "noedb_planner"
path = "src/lib.rs"

[dependencies]
noedb-lexer   = { workspace = true }
noedb-ast     = { workspace = true }
noedb-storage = { workspace = true }
rayon         = { workspace = true }

[dev-dependencies]
noedb-parser = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "query"
harness = false

[lints]
workspace = true
