// NoeDB SQL API v1 — unary gRPC over HTTP/2 + TLS/mTLS (Phase 1 Week 3).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: noedb/v1/sql.proto

package noedbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SqlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlRequest) Reset() {
	*x = SqlRequest{}
	mi := &file_noedb_v1_sql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlRequest) ProtoMessage() {}

func (x *SqlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlRequest.ProtoReflect.Descriptor instead.
func (*SqlRequest) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{0}
}

func (x *SqlRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_noedb_v1_sql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{1}
}

type SqlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SqlResponse_Result
	//	*SqlResponse_Explain
	//	*SqlResponse_Pong
	//	*SqlResponse_Error
	Body          isSqlResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlResponse) Reset() {
	*x = SqlResponse{}
	mi := &file_noedb_v1_sql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlResponse) ProtoMessage() {}

func (x *SqlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlResponse.ProtoReflect.Descriptor instead.
func (*SqlResponse) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{2}
}

func (x *SqlResponse) GetBody() isSqlResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SqlResponse) GetResult() *ResultSet {
	if x != nil {
		if x, ok := x.Body.(*SqlResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *SqlResponse) GetExplain() string {
	if x != nil {
		if x, ok := x.Body.(*SqlResponse_Explain); ok {
			return x.Explain
		}
	}
	return ""
}

func (x *SqlResponse) GetPong() *Empty {
	if x != nil {
		if x, ok := x.Body.(*SqlResponse_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *SqlResponse) GetError() *SqlError {
	if x != nil {
		if x, ok := x.Body.(*SqlResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSqlResponse_Body interface {
	isSqlResponse_Body()
}

type SqlResponse_Result struct {
	Result *ResultSet `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type SqlResponse_Explain struct {
	Explain string `protobuf:"bytes,2,opt,name=explain,proto3,oneof"`
}

type SqlResponse_Pong struct {
	Pong *Empty `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

type SqlResponse_Error struct {
	Error *SqlError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*SqlResponse_Result) isSqlResponse_Body() {}

func (*SqlResponse_Explain) isSqlResponse_Body() {}

func (*SqlResponse_Pong) isSqlResponse_Body() {}

func (*SqlResponse_Error) isSqlResponse_Body() {}

type ResultSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultSet) Reset() {
	*x = ResultSet{}
	mi := &file_noedb_v1_sql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultSet) ProtoMessage() {}

func (x *ResultSet) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultSet.ProtoReflect.Descriptor instead.
func (*ResultSet) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{3}
}

func (x *ResultSet) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ResultSet) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_noedb_v1_sql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

type SqlError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqlError) Reset() {
	*x = SqlError{}
	mi := &file_noedb_v1_sql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqlError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqlError) ProtoMessage() {}

func (x *SqlError) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqlError.ProtoReflect.Descriptor instead.
func (*SqlError) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{5}
}

func (x *SqlError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SqlError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_noedb_v1_sql_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_noedb_v1_sql_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_noedb_v1_sql_proto_rawDescGZIP(), []int{6}
}

var File_noedb_v1_sql_proto protoreflect.FileDescriptor

var file_noedb_v1_sql_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x71, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x22, 0x22,
	0x0a, 0x0a, 0x53, 0x71, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x53, 0x71, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1a, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x07, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x25, 0x0a, 0x04,
	0x70, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x6f, 0x65,
	0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x48, 0x00, 0x52, 0x04, 0x70,
	0x6f, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x71,
	0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x48, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x53, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x21,
	0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e,
	0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77,
	0x73, 0x22, 0x1b, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x65, 0x6c, 0x6c,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63, 0x65, 0x6c, 0x6c, 0x73, 0x22, 0x38,
	0x0a, 0x08, 0x53, 0x71, 0x6c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x32, 0xab, 0x01, 0x0a, 0x03, 0x53, 0x71, 0x6c, 0x12, 0x36, 0x0a, 0x07, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x71, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x65,
	0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x71, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x6e,
	0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x71, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x71,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x15, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x6f, 0x65, 0x64, 0x62,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x71, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f,
	0x72, 0x69, 0x79, 0x61, 0x6d, 0x61, 0x32, 0x33, 0x37, 0x2f, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2d,
	0x67, 0x6f, 0x2f, 0x6e, 0x6f, 0x65, 0x64, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x6e, 0x6f, 0x65, 0x64,
	0x62, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_noedb_v1_sql_proto_rawDescOnce sync.Once
	file_noedb_v1_sql_proto_rawDescData []byte
)

func file_noedb_v1_sql_proto_rawDescGZIP() []byte {
	file_noedb_v1_sql_proto_rawDescOnce.Do(func() {
		file_noedb_v1_sql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_noedb_v1_sql_proto_rawDesc), len(file_noedb_v1_sql_proto_rawDesc)))
	})
	return file_noedb_v1_sql_proto_rawDescData
}

var file_noedb_v1_sql_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_noedb_v1_sql_proto_goTypes = []any{
	(*SqlRequest)(nil),  // 0: noedb.v1.SqlRequest
	(*PingRequest)(nil), // 1: noedb.v1.PingRequest
	(*SqlResponse)(nil), // 2: noedb.v1.SqlResponse
	(*ResultSet)(nil),   // 3: noedb.v1.ResultSet
	(*Row)(nil),         // 4: noedb.v1.Row
	(*SqlError)(nil),    // 5: noedb.v1.SqlError
	(*Empty)(nil),       // 6: noedb.v1.Empty
}
var file_noedb_v1_sql_proto_depIdxs = []int32{
	3, // 0: noedb.v1.SqlResponse.result:type_name -> noedb.v1.ResultSet
	6, // 1: noedb.v1.SqlResponse.pong:type_name -> noedb.v1.Empty
	5, // 2: noedb.v1.SqlResponse.error:type_name -> noedb.v1.SqlError
	4, // 3: noedb.v1.ResultSet.rows:type_name -> noedb.v1.Row
	0, // 4: noedb.v1.Sql.Execute:input_type -> noedb.v1.SqlRequest
	0, // 5: noedb.v1.Sql.Explain:input_type -> noedb.v1.SqlRequest
	1, // 6: noedb.v1.Sql.Ping:input_type -> noedb.v1.PingRequest
	2, // 7: noedb.v1.Sql.Execute:output_type -> noedb.v1.SqlResponse
	2, // 8: noedb.v1.Sql.Explain:output_type -> noedb.v1.SqlResponse
	2, // 9: noedb.v1.Sql.Ping:output_type -> noedb.v1.SqlResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_noedb_v1_sql_proto_init() }
func file_noedb_v1_sql_proto_init() {
	if File_noedb_v1_sql_proto != nil {
		return
	}
	file_noedb_v1_sql_proto_msgTypes[2].OneofWrappers = []any{
		(*SqlResponse_Result)(nil),
		(*SqlResponse_Explain)(nil),
		(*SqlResponse_Pong)(nil),
		(*SqlResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_noedb_v1_sql_proto_rawDesc), len(file_noedb_v1_sql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_noedb_v1_sql_proto_goTypes,
		DependencyIndexes: file_noedb_v1_sql_proto_depIdxs,
		MessageInfos:      file_noedb_v1_sql_proto_msgTypes,
	}.Build()
	File_noedb_v1_sql_proto = out.File
	file_noedb_v1_sql_proto_goTypes = nil
	file_noedb_v1_sql_proto_depIdxs = nil
}
