// NoeDB SQL API v1 — unary gRPC over HTTP/2 + TLS/mTLS (Phase 1 Week 3).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: noedb/v1/sql.proto

package noedbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sql_Execute_FullMethodName = "/noedb.v1.Sql/Execute"
	Sql_Explain_FullMethodName = "/noedb.v1.Sql/Explain"
	Sql_Ping_FullMethodName    = "/noedb.v1.Sql/Ping"
)

// SqlClient is the client API for Sql service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Cluster-authenticated SQL service (auth via `x-noedb-auth` metadata).
type SqlClient interface {
	Execute(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error)
	Explain(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*SqlResponse, error)
}

type sqlClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlClient(cc grpc.ClientConnInterface) SqlClient {
	return &sqlClient{cc}
}

func (c *sqlClient) Execute(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlResponse)
	err := c.cc.Invoke(ctx, Sql_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) Explain(ctx context.Context, in *SqlRequest, opts ...grpc.CallOption) (*SqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlResponse)
	err := c.cc.Invoke(ctx, Sql_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*SqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SqlResponse)
	err := c.cc.Invoke(ctx, Sql_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlServer is the server API for Sql service.
// All implementations must embed UnimplementedSqlServer
// for forward compatibility.
//
// Cluster-authenticated SQL service (auth via `x-noedb-auth` metadata).
type SqlServer interface {
	Execute(context.Context, *SqlRequest) (*SqlResponse, error)
	Explain(context.Context, *SqlRequest) (*SqlResponse, error)
	Ping(context.Context, *PingRequest) (*SqlResponse, error)
	mustEmbedUnimplementedSqlServer()
}

// UnimplementedSqlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlServer struct{}

func (UnimplementedSqlServer) Execute(context.Context, *SqlRequest) (*SqlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSqlServer) Explain(context.Context, *SqlRequest) (*SqlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedSqlServer) Ping(context.Context, *PingRequest) (*SqlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSqlServer) mustEmbedUnimplementedSqlServer() {}
func (UnimplementedSqlServer) testEmbeddedByValue()             {}

// UnsafeSqlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlServer will
// result in compilation errors.
type UnsafeSqlServer interface {
	mustEmbedUnimplementedSqlServer()
}

func RegisterSqlServer(s grpc.ServiceRegistrar, srv SqlServer) {
	// If the following call pancis, it indicates UnimplementedSqlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sql_ServiceDesc, srv)
}

func _Sql_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sql_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).Execute(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sql_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).Explain(ctx, req.(*SqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sql_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sql_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sql_ServiceDesc is the grpc.ServiceDesc for Sql service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sql_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noedb.v1.Sql",
	HandlerType: (*SqlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _Sql_Execute_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _Sql_Explain_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Sql_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noedb/v1/sql.proto",
}
